config/routes.rb
Rails.application.routes.draw do


  # GoodJob
  authenticate :user, ->(user) { user.super? } do
    mount GoodJob::Engine => 'good_job'
  end

  ## Devise/Auth
  # devise_for :users, path_names: { sign_in: 'login', edit: 'profile' }
  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "static#index"

  get 'dashboard', to: 'dashboard#index'
  post 'trigger_sample_job', to: 'dashboard#trigger_sample_job', as: 'dashboard_trigger_sample_job'

  post '/stripe/webhooks', to: 'stripe#webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/cable_broadcastable.rb
# NOTE: Not only are broadcasts happening on create/update,
# but on subscribe, the broadcast_schema methods are manually called
# so when they're update anywhere, ensure to check both places

module CableBroadcastable
  extend ActiveSupport::Concern

  included do
    after_commit :broadcast, on: [:create, :update], if: :any_changes?
    after_destroy :broadcast
  end

  def broadcast
    bc = broadcast_schema

    raise "No channels to broadcast" if bc.nil?
    raise "broadcast_schema should be an Array, got: #{bc.class}" unless bc.is_a?(Array)
    return if bc.empty?

    bc.each do |schema|
      raise "schema should be a Hash, got: #{schema.class}" unless schema.is_a?(Hash)
      raise "Missing channel or data for broadcast_schema: #{schema}" unless schema[:channel] && schema[:data]

      ActionCable.server.broadcast(schema[:channel], Oj.dump(schema[:data]))
    end
  end

  def object_serialize
    raise NotImplementedError
  end

  def broadcast_schema
    raise NotImplementedError
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  has_one :character
  has_many :sessions, foreign_key: 'host_user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def trigger_sample_job
    SampleJob.perform_later
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :redirect_authenticate

  def index
  end

  private

  def redirect_authenticate
    return if current_user.blank?

    redirect_to dashboard_path
  end
end

app/controllers/stripe_controller.rb
class Api::StripeController < ApplicationController
  # before_action :api_authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:webhooks]

  def webhooks
    endpoint_secret = ENV['STRIPE_TOKEN_WEBHOOK_SECRET']
    sig_header = request.env['HTTP_STRIPE_SIGNATURE']
    payload = request.body.read
    event = nil

    raise "No endpoint_secret for #{self.class.name}" if endpoint_secret.nil?
    raise "No sig_header for #{self.class.name}" if sig_header.nil?
    raise "No payload for #{self.class.name}" if payload.nil?

    begin
      event = Stripe::Webhook.construct_event(
        payload, sig_header, endpoint_secret
      )
    rescue JSON::ParserError => err
      Sentry.capture_exception(err)
      return head :bad_request
    rescue Stripe::SignatureVerificationError => err
      Sentry.capture_exception(err)
      return head :bad_request
    end

    # Handle the event
    # (These events are defined in the stripe webook setup so they are not arbitrary)
    case event.type
    when 'charge.refunded' # Not sure if we care about this really (or even possible) but can remove if uneeded later
      charge = event.data.object
      Sentry.capture_message("Charge refunded: #{charge.id}")
    when 'checkout.session.completed' # Checkout completed (via payment link, for example)
      session = event.data.object # Stripe::Checkout::Session


      client_reference_id = session.client_reference_id # User ID (UUID) passed via payment link on tokens purchase page
      raise "No client_reference_id for #{self.class.name}" if client_reference_id.nil?

      user = User.find_by(id: client_reference_id)
      raise "No user for client_reference_id #{client_reference_id}" if user.nil?

      # Verify that this payment link still exists
      payment_link_id = session.payment_link # Payment ID string (not the url)
      payment_link_in_stripe = Stripe::PaymentLink.list.any? do |payment_link|
        payment_link.id == payment_link_id
      end
      raise "No payment link in Stripe for #{payment_link_id}" unless payment_link_in_stripe

      product_set = StripeCharges::TOKEN_PURCHASE_LINKS[Rails.env.to_sym].values.find do |link|
        link[:plink] == payment_link_id
      end
      raise "No product set for Stripe payment_link_id: #{payment_link_id}" if product_set.nil?

      # Perform checkout logic
    else
      puts "Unhandled event type: #{event.type}"
    end

    head :ok
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<main class="mv4">
  App entrypoint.

  <%= link_to 'Trigger Sample job', dashboard_trigger_sample_job_path, method: :post %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blueprint</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <meta name="turbo-prefetch" content="false">
    <meta name="turbo-cache-control" content="no-cache">
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>

    <script type="text/javascript">
      window.application_host = '<%= ENV['APPLICATION_HOST'] %>';
      window.rails_env = '<%= Rails.env %>';
      window.debug = window.location.hostname === 'localhost';

      window.sendFetchRequest = function (url, options) {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').content;
        if (!csrfToken) throw new Error('CSRF token not found!');

        options = options || {};
        options.headers = options.headers || { 'Content-Type': 'application/json' };
        options.headers['X-CSRF-Token'] = csrfToken;

        return fetch(url, options)
          .then(response => {
            return response.json();
          })
          .catch(error => {
            console.error('Fetch error:', error.message);
            throw error;
          });
        };
    </script>
  </head>

  <body>
    <nav>
      <section class="flex items-center pv2">
        <a href="/" class='fg1'>Blueprint</a>

        <% if current_user %>
          <%= link_to 'Profile', edit_user_registration_path, class: 'button is-link' %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'button is-link' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'button' %>
        <% end %>
      </section>
    </nav>
    
    <nav>
      <% if notice %><p class="box is-narrow notice"><%= notice %></p><% end %>
      <% if alert %><p class="box is-narrow is-alert alert"><%= alert %></p><% end %>
    </nav>

    <%= yield %>
  </body>
</html>